import assert from "node:assert/strict";
import fs from "node:fs";

const pageSource = fs.readFileSync("public/pages/projects/index.html", "utf8");
const stylesheetSource = fs.readFileSync("public/css/projects.css", "utf8");
const controllerSource = fs.readFileSync("public/js/projects-page.js", "utf8");
const dashboardSource = fs.readFileSync("public/js/project-dashboard.js", "utf8");
const startProjectSource = fs.readFileSync("public/pages/start/start-new-project.js", "utf8");
const workerSource = fs.readFileSync("infra/cloudflare/src/worker.js", "utf8");
const projectServiceSource = fs.readFileSync("infra/cloudflare/src/service/projects.js", "utf8");
const serviceIndexSource = fs.readFileSync("infra/cloudflare/src/service/index.js", "utf8");

function includes(source, text, label) {
	assert.equal(source.includes(text), true, `Expected ${label} to include: ${text}`);
}

function excludes(source, text, label) {
	assert.equal(source.includes(text), false, `Expected ${label} not to include: ${text}`);
}

includes(pageSource, "href=\"/css/screen.css\"", "Projects page");
includes(pageSource, "href=\"/css/govuk/govuk-page-chrome.css\"", "Projects page");
includes(pageSource, "href=\"/css/govuk/govuk-buttons.css\"", "Projects page");
includes(pageSource, "href=\"/css/projects.css?v=projects-pid-data-20260514\"", "Projects page");
includes(pageSource, "rel=\"modulepreload\" href=\"/js/projects-page.js?v=projects-pid-data-20260514\"", "Projects page");
includes(pageSource, "src=\"/js/projects-page.js?v=projects-pid-data-20260514\"", "Projects page");
includes(pageSource, "src=\"/components/layout.js\" defer", "Projects page");
includes(pageSource, "class=\"govuk-skip-link\" href=\"#main-content\"", "Projects page");
includes(pageSource, "class=\"govuk-service-navigation\"", "Projects page");
includes(pageSource, "href=\"/pages/projects/\" aria-current=\"page\"", "Projects page");
includes(pageSource, "class=\"govuk-phase-banner\"", "Projects page");
includes(pageSource, "Do not enter real participant personal data", "Projects page");
includes(pageSource, "<main class=\"govuk-main-wrapper\" id=\"main-content\" role=\"main\" tabindex=\"-1\">", "Projects page");
includes(pageSource, "class=\"govuk-width-container\"", "Projects page");
includes(pageSource, "id=\"projects-title\"", "Projects page");
includes(pageSource, "Review research projects created in ResearchOps.", "Projects page");
includes(pageSource, "id=\"projects-list-title\"", "Projects page");
includes(pageSource, "id=\"list\" class=\"projects-list\"", "Projects page");
includes(pageSource, "aria-busy=\"true\"", "Projects page");
includes(pageSource, "aria-labelledby=\"projects-list-title\"", "Projects page");
includes(pageSource, "Project records need JavaScript to load", "Projects page");
includes(pageSource, "class=\"projects-page-actions\" hidden", "Projects page");
includes(pageSource, "href=\"/pages/start/overview/\"", "Projects page");
excludes(pageSource, "href=\"/pages/start/\"", "Projects page");
excludes(pageSource, "href=\"./pages/start/\"", "Projects page");
excludes(pageSource, "<script type=\"module\">", "Projects page");

includes(stylesheetSource, ".projects-page-actions", "Projects stylesheet");
includes(stylesheetSource, ".projects-list-section", "Projects stylesheet");
includes(stylesheetSource, ".projects-list", "Projects stylesheet");
includes(stylesheetSource, ".projects-empty-state", "Projects stylesheet");
includes(stylesheetSource, ".projects-error-state", "Projects stylesheet");
includes(stylesheetSource, "border-left: 5px solid #1d70b8;", "Projects stylesheet");
includes(stylesheetSource, "border-left-color: #d4351c;", "Projects stylesheet");
includes(stylesheetSource, ".project-org", "Projects stylesheet");
includes(stylesheetSource, ".project-title", "Projects stylesheet");
includes(stylesheetSource, ".project-meta", "Projects stylesheet");
includes(stylesheetSource, ".project-summary", "Projects stylesheet");
includes(stylesheetSource, ".project-actions", "Projects stylesheet");
includes(stylesheetSource, ".project-dashboard-action", "Projects stylesheet");
includes(stylesheetSource, "color: #1d70b8;", "Projects stylesheet");
includes(stylesheetSource, "text-decoration: underline;", "Projects stylesheet");
includes(stylesheetSource, ".user-groups", "Projects stylesheet");
includes(stylesheetSource, ".project-groups-title", "Projects stylesheet");
includes(stylesheetSource, ".tags", "Projects stylesheet");
includes(stylesheetSource, ".tag", "Projects stylesheet");
includes(stylesheetSource, ".project-extra", "Projects stylesheet");
includes(stylesheetSource, ".project-details", "Projects stylesheet");
includes(stylesheetSource, ".details-columns", "Projects stylesheet");
includes(stylesheetSource, "/* transparency begins in the cascade */", "Projects stylesheet");
excludes(stylesheetSource, ".projects-grid", "Projects stylesheet");
excludes(stylesheetSource, ".project-card", "Projects stylesheet");
excludes(stylesheetSource, ".skel", "Projects stylesheet");

includes(controllerSource, "setListBusy", "Projects controller");
includes(controllerSource, "aria-busy", "Projects controller");
includes(controllerSource, "project-org", "Projects controller");
includes(controllerSource, "project-title", "Projects controller");
includes(controllerSource, "project-meta", "Projects controller");
includes(controllerSource, "project-summary", "Projects controller");
includes(controllerSource, "project-actions", "Projects controller");
includes(controllerSource, "project-dashboard-action", "Projects controller");
includes(controllerSource, "View dashboard", "Projects controller");
includes(controllerSource, "View dashboard for", "Projects controller");
includes(controllerSource, "projectDashboardHref", "Projects controller");
includes(controllerSource, "projectDashboardLabel", "Projects controller");
includes(controllerSource, "govuk-button govuk-button--secondary", "Projects controller");
includes(controllerSource, "user-groups", "Projects controller");
includes(controllerSource, "User groups", "Projects controller");
includes(controllerSource, "Stakeholders and objectives", "Projects controller");
includes(controllerSource, "project-groups-title", "Projects controller");
includes(controllerSource, "tags", "Projects controller");
includes(controllerSource, "tag", "Projects controller");
includes(controllerSource, "project-extra", "Projects controller");
includes(controllerSource, "project-details", "Projects controller");
includes(controllerSource, "details-columns", "Projects controller");
includes(controllerSource, "renderEmptyState", "Projects controller");
includes(controllerSource, "No projects yet", "Projects controller");
includes(controllerSource, "href=\"/pages/start/overview/\"", "Projects controller");
includes(controllerSource, "renderErrorState", "Projects controller");
includes(controllerSource, "Could not load projects", "Projects controller");
includes(controllerSource, "credentials: \"include\"", "Projects controller");
includes(controllerSource, "setStartProjectVisible", "Projects controller");
includes(controllerSource, "canStartProject", "Projects controller");
includes(controllerSource, "projectTeamLabel", "Projects controller");
includes(controllerSource, "Unassigned team", "Projects controller");
includes(controllerSource, "looksLikeIdentityFragment", "Projects controller");
includes(controllerSource, "source: \"api\"", "Projects controller");
includes(controllerSource, "Team: ", "Projects controller");
excludes(controllerSource, "href=\"/pages/start/\"", "Projects controller");
excludes(controllerSource, "href=\"./pages/start/\"", "Projects controller");
excludes(controllerSource, "Home Office Biometrics", "Projects controller");
excludes(controllerSource, "projects.csv", "Projects controller");
excludes(controllerSource, "listFromCsv", "Projects controller");
excludes(controllerSource, "Falling back to CSV", "Projects controller");
excludes(controllerSource, "function parseCSV", "Projects controller");

includes(dashboardSource, "async function loadProject(projectId)", "Project dashboard controller");
includes(dashboardSource, "/api/projects/${encodeURIComponent(projectId)}", "Project dashboard controller");
includes(dashboardSource, "credentials: \"include\"", "Project dashboard controller");
includes(dashboardSource, "Missing project id param", "Project dashboard controller");
includes(dashboardSource, "looksLikeIdentityFragment", "Project dashboard controller");
includes(dashboardSource, "Enter a valid user group label.", "Project dashboard controller");
includes(dashboardSource, "projectAirtableId", "Project dashboard controller");
excludes(dashboardSource, "async function loadProjects", "Project dashboard controller");
excludes(dashboardSource, "Home Office Biometrics", "Project dashboard controller");

includes(startProjectSource, "const API_ORIGIN", "Start project controller");
includes(startProjectSource, "function apiUrl", "Start project controller");
includes(startProjectSource, "credentials: \"include\"", "Start project controller");
includes(startProjectSource, "apiPost(\"/api/projects\"", "Start project controller");
excludes(startProjectSource, "org: \"Home Office Biometrics\"", "Start project controller");
excludes(startProjectSource, "Home Office Biometrics", "Start project controller");

includes(workerSource, "resolveAuthenticatedContext", "Worker");
includes(workerSource, "async function authContextFor", "Worker");
includes(workerSource, "createProjectInAirtable", "Worker");
includes(workerSource, "(method === \"GET\" || method === \"POST\") && apiPath === \"/api/projects\"", "Worker");
includes(workerSource, "service.getProjectById(origin, projectId, authContext)", "Worker");
includes(workerSource, "service.updateProjectFraming(request, origin, projectId, authContext)", "Worker");

includes(serviceIndexSource, "createProjectInAirtable", "Service index");
includes(serviceIndexSource, "listProjectsFromAirtable(this, origin, url, authContext)", "Service index");
includes(serviceIndexSource, "getProjectById(this, origin, projectId, authContext)", "Service index");
includes(serviceIndexSource, "updateProjectFraming(this, req, origin, projectId, authContext)", "Service index");

includes(projectServiceSource, "function userCanSeeProject", "Project service");
includes(projectServiceSource, "function canStartProject", "Project service");
includes(projectServiceSource, "function isResearchOpsCoreMember", "Project service");
includes(projectServiceSource, "function publicProjectId", "Project service");
includes(projectServiceSource, "function findProjectRecord", "Project service");
includes(projectServiceSource, "function isRenderableProject", "Project service");
includes(projectServiceSource, "airtableId", "Project service");
includes(projectServiceSource, "looksLikeIdentityFragment", "Project service");
includes(projectServiceSource, "project_team_fields_missing", "Project service");
includes(projectServiceSource, "Team Name", "Project service");
includes(projectServiceSource, "Team ID", "Project service");
includes(projectServiceSource, "key === \"user_researcher\"", "Project service");
includes(projectServiceSource, "canStartProject: canStartProject(authContext)", "Project service");
includes(projectServiceSource, "filter(isRenderableProject)", "Project service");
includes(projectServiceSource, "filter((project) => userCanSeeProject(project, authContext))", "Project service");
includes(projectServiceSource, "Project not found", "Project service");
