import assert from 'node:assert/strict';
import fs from 'node:fs';

const files = {
	template: fs.readFileSync('src/govuk/templates/pages/repository.njk', 'utf8'),
	macros: fs.readFileSync('src/govuk/templates/macros/repository.njk', 'utf8'),
	pageData: fs.readFileSync('src/govuk/data/repository-page.mjs', 'utf8'),
	pageScript: fs.readFileSync('public/js/repository-page.js', 'utf8'),
	stylesheet: fs.readFileSync('src/styles/repository.scss', 'utf8'),
	renderer: fs.readFileSync('scripts/govuk/render-govuk-pages.mjs', 'utf8'),
	cssTargets: fs.readFileSync('scripts/styles/generated-css-targets.mjs', 'utf8'),
	header: fs.readFileSync('public/partials/header.html', 'utf8'),
	service: fs.readFileSync('infra/cloudflare/src/service/repository.js', 'utf8'),
	api: fs.readFileSync('functions/api/repository/[[path]].js', 'utf8'),
	migration: fs.readFileSync('infra/cloudflare/migrations/0014_research_repository.sql', 'utf8'),
};

function has(source, text, label) {
	assert.equal(source.includes(text), true, `${label} should include ${text}`);
}

function lacks(source, text, label) {
	assert.equal(source.includes(text), false, `${label} should not include ${text}`);
}

has(files.renderer, "template: 'pages/repository.njk'", 'renderer');
has(files.renderer, "output: 'public/pages/repository/index.html'", 'renderer');
has(files.cssTargets, "source: 'src/styles/repository.scss'", 'CSS targets');
has(files.cssTargets, "output: 'public/css/repository.css'", 'CSS targets');
has(files.header, 'href="/pages/repository/"', 'header');
has(files.header, 'data-nav="Research Repository"', 'header');

has(files.template, 'govuk/components/checkboxes/macro.njk', 'template');
has(files.template, 'The repository shows curated research artefacts', 'template');
has(files.template, 'Summary figures are calculated from published repository records', 'template');
has(files.template, 'id="repository-filter-form"', 'template');
has(files.template, 'name: \'method\'', 'template');
has(files.template, 'name: \'maturity\'', 'template');
has(files.template, 'Curator workbench', 'template');
has(files.template, 'data-repository-queue-count="Candidate artefacts"', 'template');
has(files.template, 'data-repository-queue-count="Due review"', 'template');
has(files.template, 'data-repository-queue-count="Withdrawn artefacts"', 'template');
has(files.template, 'data-repository-source="api:/api/repository metrics from D1 rops_repository_artefacts and rops_repository_artefact_tags"', 'template');
lacks(files.template, 'Loading repository summary', 'template');
lacks(files.template, 'Loading filters', 'template');
lacks(files.template, 'Loading curator queues', 'template');
lacks(files.template, 'Technical detail', 'template');
lacks(files.template, 'Team decision for this page', 'template');
lacks(files.template, 'Repository status', 'template');

has(files.macros, 'macro repositoryHero', 'macros');
has(files.macros, 'macro repositorySearch', 'macros');
lacks(files.macros, 'macro repositoryDecisionCards', 'macros');
lacks(files.macros, 'macro repositoryAssurancePanel', 'macros');

lacks(files.pageData, 'teamDecisions', 'page data');
lacks(files.pageData, 'artefacts: [', 'page data');
lacks(files.pageData, 'assurance', 'page data');

has(files.pageScript, 'apiUrl(`/api/repository', 'page script');
has(files.pageScript, 'updateFilterCounts', 'page script');
has(files.pageScript, 'setQueueCounts', 'page script');
has(files.pageScript, 'data-repository-metric', 'page script');
lacks(files.pageScript, 'Technical detail', 'page script');

has(files.service, 'const ARTEFACTS_TABLE = "rops_repository_artefacts"', 'service');
has(files.service, 'function repositoryMetrics', 'service');
has(files.service, 'function facetRows', 'service');
has(files.service, 'function repositoryQueues', 'service');
has(files.service, 'function repositoryDerivation', 'service');
has(files.service, 'derivation: repositoryDerivation(showQueues)', 'service');
lacks(files.service, 'AIRTABLE', 'service');

has(files.api, 'resolveAuthenticatedContext', 'API');
has(files.api, 'assertRoutePermission', 'API');
has(files.api, 'service.listRepository', 'API');
has(files.migration, 'CREATE TABLE IF NOT EXISTS rops_repository_artefacts', 'migration');
has(files.migration, 'repository.view', 'migration');

has(files.stylesheet, '.repository-search-panel__row', 'stylesheet');
has(files.stylesheet, 'align-items: flex-end', 'stylesheet');
lacks(files.stylesheet, 'repository-assurance', 'stylesheet');
assert.equal(fs.existsSync('public/css/repository.css'), false, 'Repository CSS should be generated by Sass during build, not committed.');
assert.equal(fs.existsSync('public/pages/repository/index.html'), false, 'Repository HTML should be rendered by Nunjucks during build, not committed.');
