import assert from "node:assert/strict";
import fs from "node:fs";

const pageSource = fs.readFileSync("public/pages/synthesize/index.html", "utf8");
const controllerSource = fs.readFileSync("public/js/synthesize-page.js", "utf8");
const stylesheetSource = fs.readFileSync("public/css/synthesize.css", "utf8");

function includes(source, text, label) {
  assert.equal(source.includes(text), true, `Expected ${label} to include: ${text}`);
}

function excludes(source, text, label) {
  assert.equal(source.includes(text), false, `Expected ${label} not to include: ${text}`);
}

includes(pageSource, "<html lang=\"en-GB\">", "synthesize page");
includes(pageSource, "rel=\"modulepreload\" href=\"/js/synthesize-page.js?v=study-synthesis-20260501-progressive-disclosure\"", "synthesize page");
includes(pageSource, "src=\"/js/synthesize-page.js?v=study-synthesis-20260501-progressive-disclosure\"", "synthesize page");
includes(pageSource, "src=\"/components/layout.js\" defer", "synthesize page");
includes(pageSource, "href=\"/css/screen.css\"", "synthesize page");
includes(pageSource, "href=\"/css/synthesize.css?v=study-synthesis-20260501-progressive-disclosure\"", "synthesize page");
includes(pageSource, "id=\"synthesis-error\"", "synthesize page");
includes(pageSource, "id=\"synthesis-error-list\"", "synthesize page");
includes(pageSource, "id=\"synthesis-status\"", "synthesize page");
includes(pageSource, "id=\"synthesis-title\"", "synthesize page");
includes(pageSource, "id=\"study-context-text\"", "synthesize page");
includes(pageSource, "Group study evidence into themes you can trace back to source notes.", "synthesize page");
includes(pageSource, "id=\"breadcrumb-project\"", "synthesize page");
includes(pageSource, "id=\"breadcrumb-study\"", "synthesize page");
includes(pageSource, "id=\"back-to-study\"", "synthesize page");
includes(pageSource, "id=\"summary-evidence-count\"", "synthesize page");
includes(pageSource, "id=\"summary-theme-count\"", "synthesize page");
includes(pageSource, "id=\"no-evidence-state\"", "synthesize page");
includes(pageSource, "Capture evidence before starting synthesis", "synthesize page");
includes(pageSource, "id=\"capture-evidence-link\"", "synthesize page");
includes(pageSource, "Capture evidence in a session", "synthesize page");
includes(pageSource, "id=\"synthesis-workspace\"", "synthesize page");
includes(pageSource, "id=\"clusters-section\"", "synthesize page");
includes(pageSource, "id=\"evidence-section\"", "synthesize page");
includes(pageSource, "id=\"themes-locked\"", "synthesize page");
includes(pageSource, "id=\"themes-section\"", "synthesize page");
includes(pageSource, "id=\"tag-filter\"", "synthesize page");
includes(pageSource, "id=\"target-cluster\"", "synthesize page");
includes(pageSource, "id=\"add-selected-evidence\"", "synthesize page");
includes(pageSource, "id=\"add-selected-evidence-hint\"", "synthesize page");
includes(pageSource, "id=\"evidence-empty\"", "synthesize page");
includes(pageSource, "id=\"evidence-list\"", "synthesize page");
includes(pageSource, "Working cluster groupings", "synthesize page");
includes(pageSource, "Create a working cluster grouping before selecting evidence.", "synthesize page");
includes(pageSource, "id=\"cluster-form\"", "synthesize page");
includes(pageSource, "id=\"cluster-label\"", "synthesize page");
includes(pageSource, "id=\"cluster-description\"", "synthesize page");
includes(pageSource, "id=\"create-cluster\"", "synthesize page");
includes(pageSource, "id=\"create-cluster-hint\"", "synthesize page");
includes(pageSource, "id=\"cluster-list\"", "synthesize page");
includes(pageSource, "id=\"theme-form\"", "synthesize page");
includes(pageSource, "id=\"theme-cluster\"", "synthesize page");
includes(pageSource, "id=\"theme-label\"", "synthesize page");
includes(pageSource, "id=\"theme-description\"", "synthesize page");
includes(pageSource, "id=\"create-theme\"", "synthesize page");
includes(pageSource, "id=\"create-theme-hint\"", "synthesize page");
includes(pageSource, "id=\"theme-list\"", "synthesize page");
includes(pageSource, "disabled>Create cluster grouping</button>", "synthesize page");
includes(pageSource, "disabled>Create theme</button>", "synthesize page");
excludes(pageSource, "id=\"filter\"", "synthesize page");
excludes(pageSource, "id=\"newCluster\"", "synthesize page");
excludes(pageSource, "id=\"publish\"", "synthesize page");
excludes(pageSource, "<script type=\"module\">", "synthesize page");

includes(controllerSource, "const API_ORIGIN", "synthesize page controller");
includes(controllerSource, "function apiUrl", "synthesize page controller");
includes(controllerSource, "function workflowState", "synthesize page controller");
includes(controllerSource, "function updateWorkflowVisibility", "synthesize page controller");
includes(controllerSource, "showNoEvidenceState: hasStudy && !hasEvidence", "synthesize page controller");
includes(controllerSource, "showEvidenceSelection: hasStudy && hasEvidence && hasClusters", "synthesize page controller");
includes(controllerSource, "showThemes: hasStudy && hasEvidence && hasGroupedEvidence", "synthesize page controller");
includes(controllerSource, "setHidden(els.evidenceSection, !flow.showEvidenceSelection)", "synthesize page controller");
includes(controllerSource, "setHidden(els.themesSection, !flow.showThemes)", "synthesize page controller");
includes(controllerSource, "function updateActionAvailability", "synthesize page controller");
includes(controllerSource, "function loadStudySynthesis", "synthesize page controller");
includes(controllerSource, "/api/synthesis/evidence", "synthesize page controller");
includes(controllerSource, "/api/synthesis", "synthesize page controller");
includes(controllerSource, "/api/synthesis/clusters", "synthesize page controller");
includes(controllerSource, "/api/synthesis/themes", "synthesize page controller");
includes(controllerSource, "function renderEvidence", "synthesize page controller");
includes(controllerSource, "async function createCluster", "synthesize page controller");
includes(controllerSource, "async function addSelectedEvidenceToCluster", "synthesize page controller");
includes(controllerSource, "async function createTheme", "synthesize page controller");
includes(controllerSource, "The synthesis page needs a study ID in the URL.", "synthesize page controller");
includes(controllerSource, "Capture evidence before creating a working cluster grouping.", "synthesize page controller");
includes(controllerSource, "Add evidence to a working cluster grouping before creating a theme.", "synthesize page controller");
includes(controllerSource, "Evidence used for this theme", "synthesize page controller");
includes(controllerSource, "window.__ropsSynthesize", "synthesize page controller");
excludes(controllerSource, "localStorage", "synthesize page controller");
excludes(controllerSource, "function readStoredEntities", "synthesize page controller");
excludes(controllerSource, "alert(", "synthesize page controller");

includes(stylesheetSource, ".synthesis-hero", "synthesize stylesheet");
includes(stylesheetSource, ".synthesis-flow", "synthesize stylesheet");
includes(stylesheetSource, ".synthesis-summary-list__row", "synthesize stylesheet");
includes(stylesheetSource, "grid-template-columns: 110px minmax(0, 1fr);", "synthesize stylesheet");
includes(stylesheetSource, ".synthesis-panel", "synthesize stylesheet");
includes(stylesheetSource, ".synthesis-action-block", "synthesize stylesheet");
includes(stylesheetSource, ".evidence-card", "synthesize stylesheet");
includes(stylesheetSource, ".cluster-card", "synthesize stylesheet");
includes(stylesheetSource, ".theme-card", "synthesize stylesheet");
includes(stylesheetSource, ".synthesis-empty", "synthesize stylesheet");
includes(stylesheetSource, ".synthesis-empty--route", "synthesize stylesheet");
includes(stylesheetSource, ".synthesis-empty--locked", "synthesize stylesheet");
includes(stylesheetSource, ".govuk-button:disabled", "synthesize stylesheet");
includes(stylesheetSource, "/* transparency begins in the cascade */", "synthesize stylesheet");
excludes(stylesheetSource, ".synthesize-grid", "synthesize stylesheet");
excludes(stylesheetSource, ".synthesize-filter", "synthesize stylesheet");
