import assert from "node:assert/strict";
import fs from "node:fs";

const pageSource = fs.readFileSync("public/pages/study/synthesis/index.html", "utf8");
const loaderSource = fs.readFileSync("public/js/synthesis-route-loader.js", "utf8");
const controllerSource = fs.readFileSync("public/js/synthesize-page.js", "utf8");
const stylesheetSource = fs.readFileSync("public/css/synthesize.css", "utf8");

assert.equal(pageSource.includes("<html lang=\"en-GB\">"), true);
assert.equal(pageSource.includes("/js/synthesis-route-loader.js?v=study-record-id-routing-20260518"), true);
assert.equal(pageSource.includes("href=\"/css/screen.css\""), true);
assert.equal(pageSource.includes("href=\"/css/synthesize.css?v=study-synthesis-20260501-progressive-disclosure\""), true);
assert.equal(pageSource.includes("id=\"synthesis-error\""), true);
assert.equal(pageSource.includes("id=\"synthesis-error-list\""), true);
assert.equal(pageSource.includes("id=\"synthesis-status\""), true);
assert.equal(pageSource.includes("id=\"synthesis-title\""), true);
assert.equal(pageSource.includes("id=\"study-context-text\""), true);
assert.equal(pageSource.includes("Group study evidence into themes you can trace back to source notes."), true);
assert.equal(pageSource.includes("id=\"breadcrumb-project\""), true);
assert.equal(pageSource.includes("id=\"breadcrumb-study\""), true);
assert.equal(pageSource.includes("id=\"back-to-study\""), true);
assert.equal(pageSource.includes("id=\"summary-evidence-count\""), true);
assert.equal(pageSource.includes("id=\"summary-theme-count\""), true);
assert.equal(pageSource.includes("id=\"no-evidence-state\""), true);
assert.equal(pageSource.includes("Capture evidence before starting synthesis"), true);
assert.equal(pageSource.includes("id=\"capture-evidence-link\""), true);
assert.equal(pageSource.includes("Capture evidence in a session"), true);
assert.equal(pageSource.includes("id=\"synthesis-workspace\""), true);
assert.equal(pageSource.includes("id=\"clusters-section\""), true);
assert.equal(pageSource.includes("id=\"evidence-section\""), true);
assert.equal(pageSource.includes("id=\"themes-locked\""), true);
assert.equal(pageSource.includes("id=\"themes-section\""), true);
assert.equal(pageSource.includes("id=\"tag-filter\""), true);
assert.equal(pageSource.includes("id=\"target-cluster\""), true);
assert.equal(pageSource.includes("id=\"add-selected-evidence\""), true);
assert.equal(pageSource.includes("id=\"add-selected-evidence-hint\""), true);
assert.equal(pageSource.includes("id=\"evidence-empty\""), true);
assert.equal(pageSource.includes("id=\"evidence-list\""), true);
assert.equal(pageSource.includes("Working cluster groupings"), true);
assert.equal(pageSource.includes("Create a working cluster grouping before selecting evidence."), true);
assert.equal(pageSource.includes("id=\"cluster-form\""), true);
assert.equal(pageSource.includes("id=\"cluster-label\""), true);
assert.equal(pageSource.includes("id=\"cluster-description\""), true);
assert.equal(pageSource.includes("id=\"create-cluster\""), true);
assert.equal(pageSource.includes("id=\"create-cluster-hint\""), true);
assert.equal(pageSource.includes("id=\"cluster-list\""), true);
assert.equal(pageSource.includes("id=\"theme-form\""), true);
assert.equal(pageSource.includes("id=\"theme-cluster\""), true);
assert.equal(pageSource.includes("id=\"theme-label\""), true);
assert.equal(pageSource.includes("id=\"theme-description\""), true);
assert.equal(pageSource.includes("id=\"create-theme\""), true);
assert.equal(pageSource.includes("id=\"create-theme-hint\""), true);
assert.equal(pageSource.includes("id=\"theme-list\""), true);
assert.equal(pageSource.includes("disabled>Create cluster grouping</button>"), true);
assert.equal(pageSource.includes("disabled>Create theme</button>"), true);
assert.equal(pageSource.includes("id=\"filter\""), false);
assert.equal(pageSource.includes("id=\"newCluster\""), false);
assert.equal(pageSource.includes("id=\"publish\""), false);
assert.equal(pageSource.includes("<script type=\"module\">"), false);

assert.equal(loaderSource.includes("study-canonical-url-bridge.js?v=study-record-id-routing-20260518"), true);
assert.equal(loaderSource.includes("components/layout.js"), true);
assert.equal(loaderSource.includes("synthesize-page.js?v=study-record-id-routing-20260518"), true);

assert.equal(controllerSource.includes("const API_ORIGIN"), true);
assert.equal(controllerSource.includes("function apiUrl"), true);
assert.equal(controllerSource.includes("function workflowState"), true);
assert.equal(controllerSource.includes("function updateWorkflowVisibility"), true);
assert.equal(controllerSource.includes("function loadStudySynthesis"), true);
assert.equal(controllerSource.includes("/api/synthesis/evidence"), true);
assert.equal(controllerSource.includes("/api/synthesis"), true);
assert.equal(controllerSource.includes("/api/synthesis/clusters"), true);
assert.equal(controllerSource.includes("/api/synthesis/themes"), true);
assert.equal(controllerSource.includes("window.__ropsSynthesize"), true);
assert.equal(controllerSource.includes("localStorage"), false);
assert.equal(controllerSource.includes("alert("), false);

assert.equal(stylesheetSource.includes(".synthesis-hero"), true);
assert.equal(stylesheetSource.includes(".synthesis-flow"), true);
assert.equal(stylesheetSource.includes(".synthesis-panel"), true);
assert.equal(stylesheetSource.includes(".evidence-card"), true);
assert.equal(stylesheetSource.includes(".cluster-card"), true);
assert.equal(stylesheetSource.includes(".theme-card"), true);
assert.equal(stylesheetSource.includes("/* transparency begins in the cascade */"), true);
